# Generated by Django 3.0.14 on 2021-06-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20210601_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lendet',
            old_name='krijues',
            new_name='creator',
        ),
    ]
