# Generated by Django 3.0.14 on 2021-06-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20210601_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lendet',
            old_name='klasa',
            new_name='class_obj',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='krijuar_me',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='pershkrimi',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='imazhi_lendes',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='lendet',
            old_name='titulli',
            new_name='title',
        ),
    ]
