# Generated by Django 3.0.14 on 2021-06-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20210601_2244'),
    ]

    operations = [
        migrations.RenameModel('Klasa', 'Class')
    ]
