# Generated by Django 3.0.14 on 2021-06-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20210601_2247'),
    ]

    operations = [
        migrations.RenameModel('Lendet', 'Subject')
    ]
